import type { CommonContent } from "@/lib/i18n/types";

export const commonContent: CommonContent = {
  brandName: "Health AI Platform Pro",
  brandTagline: "Clinical decision-support for modern care teams",
  nav: {
    home: "Home",
    login: "Sign in",
    register: "Create account",
    patients: "Patients",
    management: "Doctor assignments",
    logout: "Sign out",
    skipToContent: "Skip to main content",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  common: {
    loading: "LoadingÔÇĞ",
    error: "Something went wrong.",
    retry: "Try again",
    back: "Back",
    notFound: "Not found.",
    unauthorized: "Please sign in to continue.",
    forbidden: "You do not have permission to access this page.",
  },
  language: {
    switcherLabel: "Language",
  },
  footer: {
    tagline: "Secure healthcare decision-support software.",
    disclaimer:
      "This platform provides decision-support information only. It does not replace professional medical judgment.",
    copyright: "Health AI Platform Pro. All rights reserved.",
    links: {
      privacy: "Privacy",
      terms: "Terms",
      contact: "Contact",
    },
  },
  landing: {
    badge: "Clinical decision-support platform",
    heroTitle: "Smarter clinical workflows, built for care teams",
    heroDescription:
      "Coordinate patient records, health insights, and risk assessments in one secure workspace designed for healthcare professionals.",
    primaryCta: "Get started",
    secondaryCta: "Sign in",
    secondaryCtaAuthenticated: "Go to patients",
    featuresTitle: "Built for responsible healthcare AI",
    features: [
      {
        title: "Structured patient data",
        description:
          "Organize appointments, medical records, and health measurements with owner-scoped access controls.",
      },
      {
        title: "Decision-support analytics",
        description:
          "Review trends and insights that support clinical judgment without presenting diagnoses.",
      },
      {
        title: "Scalable technical foundation",
        description:
          "A modular architecture on FastAPI with JWT authentication, PostgreSQL persistence, and observability for growing clinical workloads.",
      },
    ],
    trustTitle: "Designed with clinical safety in mind",
    trustPoints: [
      "No patient identifiers in demo content",
      "Clear medical disclaimers on decision-support outputs",
      "Secure API integration via environment configuration",
    ],
  },
  auth: {
    loginTitle: "Sign in",
    loginDescription: "Access your workspace with your Health AI Platform Pro account.",
    registerTitle: "Create account",
    registerDescription: "Register a professional account connected to the FastAPI backend.",
    emailLabel: "Email address",
    emailPlaceholder: "you@clinic.example",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordPlaceholder: "Re-enter your password",
    loginSubmit: "Sign in",
    registerSubmit: "Create account",
    noAccount: "Need an account?",
    hasAccount: "Already have an account?",
    phaseNotice:
      "Decision-support only. Do not enter real patient identifiers in demo environments.",
    firstNameLabel: "First name",
    firstNamePlaceholder: "Jane",
    lastNameLabel: "Last name",
    lastNamePlaceholder: "Doe",
    loginError: "Sign in failed. Check your email and password.",
    registerError: "Registration failed. Try a different email or stronger password.",
    passwordMismatch: "Passwords do not match.",
    genericError: "Something went wrong. Please try again.",
    logout: "Sign out",
    signedInAs: "Signed in as",
  },
  patients: {
    title: "Patients",
    description: "Select a patient to review their clinical timeline.",
    empty: "No patients found. Create patients via the API or add demo data in your backend.",
    viewTimeline: "View timeline",
    viewPatient: "View patient",
    name: "Name",
    dateOfBirth: "Date of birth",
    gender: "Gender",
    loadError: "Could not load patients.",
    genders: {
      male: "Male",
      female: "Female",
      other: "Other",
    },
  },
  patientHub: {
    title: "Patient overview",
    description: "Review assigned patient details, risk history, and reports.",
    decisionSupportTitle: "Clinical decision support only",
    decisionSupportBody:
      "This system does not provide a medical diagnosis. Information is for clinical decision support and must not replace professional medical judgment.",
    clinicalTimeline: "Clinical timeline",
    downloadPdf: "Download PDF report",
    downloadingPdf: "Preparing PDF…",
    pdfError: "Could not download the PDF report.",
    pdfSuccess: "PDF download started.",
    riskHistoryTitle: "Risk assessment history",
    riskHistoryEmpty: "No risk assessments recorded for this patient yet.",
    riskHistoryLoadError: "Could not load risk assessment history.",
    riskType: "Type",
    riskLevel: "Level",
    assessedAt: "Assessed at",
    score: "Score",
    factors: "Contributing factors",
    missingInputs: "Missing inputs",
    riskDisclaimer:
      "Risk outputs are rule-based decision-support estimates, not a diagnosis or treatment plan.",
    active: "Active",
    inactive: "Inactive",
    notFoundOrDenied: "Patient not found or you do not have access to this patient.",
    loadError: "Could not load patient details.",
    assessmentTypes: {
      diabetes: "Diabetes",
      heart_disease: "Heart disease",
      stroke: "Stroke",
    },
    riskLevels: {
      low: "Low",
      moderate: "Moderate",
      elevated: "Elevated",
    },
  },
  timeline: {
    title: "Clinical timeline",
    description: "Read-only summary of recorded measurements, records, and appointments.",
    sortNotice: "Events shown oldest to newest.",
    empty: "No timeline events in the selected period.",
    loadError: "Could not load the clinical timeline.",
    truncatedNotice: "Some events were omitted because the list limit was reached.",
    filtersTitle: "Filters",
    dateFrom: "From (UTC date)",
    dateTo: "To (UTC date)",
    applyFilters: "Apply filters",
    clearFilters: "Clear filters",
    includeRiskSnapshot: "Include current risk snapshot",
    sourceKind: "Source",
    severity: "Severity",
    disclaimer:
      "This clinical timeline is an informational, read-only summary of recorded data. It is not a medical diagnosis, treatment recommendation, or substitute for professional medical judgment. Derived items are rule-based interpretations of recorded measurements and appointments. Risk snapshots reflect a single on-demand assessment at generation time, not a stored clinical history.",
    patientSummary: {
      ageSuffix: "years",
    },
    headlines: {},
    sourceKinds: {
      medical_record: "Medical record",
      health_measurement: "Health measurement",
      appointment: "Appointment",
      derived: "Derived analysis",
      risk_assessment_current_snapshot: "Current risk assessment",
    },
    severityLevels: {
      info: "Info",
      warning: "Warning",
      critical: "Critical",
    },
    detailPhrases: {},
    eventTypes: {
      medical_record_diagnosis: "Medical record",
      medical_record_treatment: "Treatment",
      medical_record_medication: "Medication",
      medical_record_hospitalization: "Hospitalization",
      health_measurement: "Measurement",
      appointment_scheduled: "Appointment",
      appointment_completed: "Completed",
      appointment_cancelled: "Cancelled",
      appointment_status: "Appointment",
      appointment_overdue: "Overdue follow-up",
      measurement_trend_derived: "Trend (derived)",
      risk_current_snapshot: "Risk snapshot",
    },
  },
  management: {
    title: "Doctor assignments",
    description:
      "Review your organization membership, list doctors, and manage patient assignments.",
    forbiddenTitle: "Access denied",
    forbiddenDescription: "This management screen is only available to clinic_admin accounts.",
    organizationSection: "Organization membership",
    doctorsSection: "Active doctors",
    patientsSection: "Select patient",
    assignmentsSection: "Current assignments",
    assignDoctor: "Assign doctor",
    removeAssignment: "Remove assignment",
    selectPatient: "Choose a patient",
    selectDoctor: "Choose a doctor",
    noPatientSelected: "Select a patient from the list to view assignments.",
    membershipId: "Membership ID",
    organizationId: "Organization ID",
    membershipRole: "Membership role",
    joinedAt: "Joined at",
    userId: "User ID",
    patientLabel: "Patient",
    isPrimary: "Primary assignment",
    status: "Status",
    assignedAt: "Assigned at",
    endedAt: "Ended at",
    assignmentId: "Assignment ID",
    assigneeUserId: "Assignee user ID",
    emptyDoctors: "No active doctors to list in your organization.",
    emptyAssignments: "No assignments recorded for this patient.",
    loadError: "Could not load management data.",
    createSuccess: "Assignment created.",
    deactivateSuccess: "Assignment deactivated.",
    membershipRoles: {
      doctor: "Doctor",
      clinic_admin: "Clinic admin",
    },
    assignmentStatuses: {
      active: "Active",
      inactive: "Inactive",
    },
    errors: {
      duplicateAssignment: "An active assignment already exists for this doctor and patient.",
      duplicatePrimary: "An active primary assignment already exists for this patient.",
      patientNotFound: "Patient not found or outside your organization.",
      assignmentNotFound: "Assignment not found.",
      doctorNotFound: "Doctor not found or outside your organization.",
      generic: "The operation could not be completed. Please try again.",
    },
  },
};

export type { CommonContent };
