import type { EncounterDetailLabels } from "@/components/patients/EncounterDetailPageContent";
import type { EncounterWorkspaceLabels } from "@/components/patients/EncounterDetailWriteWorkspace";
import type { EncounterTerminalLabels } from "@/components/patients/EncounterTerminalActions";

export function makeEncounterWorkspaceTestLabels(): EncounterWorkspaceLabels {
  return {
    recordsHeading: "Records",
    complaintsHeading: "Complaints",
    findingsHeading: "Findings",
    responsesHeading: "Responses",
    complaintsEmpty: "No complaints",
    findingsEmpty: "No findings",
    responsesEmpty: "No responses",
    readOnlyFinalized: "Read-only finalized",
    readOnlyCancelled: "Read-only cancelled",
    readOnlyDraft: "Read-only draft",
    primaryBadge: "Primary",
    negatedBadge: "Negated",
    recordedAt: "Recorded",
    complaintKeyLabel: "Key",
    complaintKeyHint: "Hint",
    complaintTextLabel: "Description",
    complaintPrimaryLabel: "Primary",
    complaintNegatedLabel: "Negated",
    addComplaint: "Add complaint",
    addComplaintPending: "Saving…",
    complaintSuccess: "Saved complaint",
    removeComplaint: "Remove",
    removeComplaintConfirm: "Confirm remove",
    removeComplaintPending: "Removing…",
    removeComplaintSuccess: "Removed",
    primaryComplaintHint: "Primary hint",
    findingTypeLabel: "Type",
    findingKeyLabel: "Finding key",
    findingKeyHint: "Finding hint",
    findingValueCodeLabel: "Code",
    findingValueNumericLabel: "Number",
    findingUnitLabel: "Unit",
    findingNegatedLabel: "Negated finding",
    findingSourceLabel: "Source",
    addFinding: "Add finding",
    addFindingPending: "Saving finding…",
    findingSuccess: "Finding saved",
    questionKeyLabel: "Question key",
    questionKeyHint: "Question hint",
    answerTypeLabel: "Answer type",
    answerCodeLabel: "Answer code",
    answerNumericLabel: "Numeric",
    booleanYes: "Yes",
    booleanNo: "No",
    booleanUnknown: "Unknown",
    clinicianNoteLabel: "Note",
    saveResponse: "Save response",
    saveResponsePending: "Saving…",
    responseSuccess: "Response saved",
    validationComplaintRequired: "Complaint required",
    validationFindingKeyRequired: "Finding key required",
    validationNumericInvalid: "Invalid number",
    validationQuestionKeyRequired: "Question key required",
    validationAnswerRequired: "Answer required",
    validationNoteRequired: "Note required",
    findingTypes: {
      symptom: "Symptom",
      physical_exam: "Physical exam",
      history_item: "History",
      risk_factor: "Risk",
      negative_finding: "Negative",
      other: "Other",
    },
    findingSources: {
      patient_reported: "Patient",
      clinician_observed: "Clinician",
      historical_record: "History",
      device: "Device",
      other: "Other",
    },
    answerTypes: {
      boolean: "Boolean",
      single_choice: "Single choice",
      number: "Number",
      text: "Text",
    },
    mutationErrors: {
      notFoundOrDenied: "Not found",
      validation: "Validation",
      conflictStale: "Conflict stale",
      terminalEdit: "Terminal",
      server: "Server",
      accessDenied: "Denied",
      generic: "Generic",
    },
  };
}

export function makeEncounterTerminalTestLabels(): EncounterTerminalLabels {
  return {
    sectionHeading: "Complete encounter",
    finalizeEncounter: "Complete encounter",
    cancelEncounter: "Cancel encounter",
    finalizePending: "Completing…",
    cancelPending: "Cancelling…",
    finalizeSuccess: "Encounter completed.",
    cancelSuccess: "Encounter cancelled.",
    finalizeConfirmTitle: "Complete this encounter",
    finalizeConfirmBody: "Confirm finalize body",
    finalizeConfirmAction: "Confirm completion",
    finalizeConfirmCancel: "Go back",
    cancelConfirmTitle: "Cancel this encounter",
    cancelConfirmBody: "Confirm cancel body",
    cancelConfirmAction: "Confirm cancellation",
    cancelConfirmCancel: "Go back",
    summarySectionKeyLabel: "Section key",
    summaryContentKeyLabel: "Content key",
    summaryClinicianTextLabel: "Encounter summary",
    summaryClinicianNoteLabel: "Clinician note",
    validationSectionKeyRequired: "Section key required",
    validationSummaryTextRequired: "Summary text required",
    finalizeValidation: "Finalize validation",
    mutationErrors: {
      notFoundOrDenied: "Not found",
      validation: "Validation",
      conflictStale: "Conflict stale",
      terminalEdit: "Terminal",
      server: "Server",
      accessDenied: "Denied",
      generic: "Generic",
    },
  };
}

export function makeEncounterDetailTestLabels(): EncounterDetailLabels {
  return {
    detailTitle: "Encounter details",
    backToPatient: "Back to patient",
    statusLabels: { finalized: "Finalized", active: "Active", draft: "Draft", cancelled: "Cancelled" },
    specialtyLabel: "Specialty",
    startedAt: "Started",
    endedAt: "Ended",
    finalSummaryHeading: "Final summary",
    detailNotFound: "Not found or denied",
    detailLoadError: "Load failed",
    notFoundOrDenied: "Not found",
    genericError: "Generic",
    accessDenied: "Denied",
    loadingLabel: "Loading…",
    retryLabel: "Retry",
    clinicianNoteLabel: "Note",
    workspace: makeEncounterWorkspaceTestLabels(),
    terminal: makeEncounterTerminalTestLabels(),
  };
}
