import type { CommonContent } from "@/lib/i18n/types";

export const commonContent: CommonContent = {
  brandName: "Health AI Platform Pro",
  brandTagline: "Modern sağlık ekipleri için klinik karar destek platformu",
  nav: {
    home: "Ana sayfa",
    login: "Giriş yap",
    register: "Hesap oluştur",
    patients: "Hastalar",
    management: "Doktor atamaları",
    logout: "Çıkış yap",
    skipToContent: "Ana içeriğe geç",
    openMenu: "Menüyü aç",
    closeMenu: "Menüyü kapat",
  },
  common: {
    loading: "Yükleniyor…",
    error: "Bir hata oluştu.",
    retry: "Tekrar dene",
    back: "Geri",
    notFound: "Bulunamadı.",
    unauthorized: "Devam etmek için giriş yapın.",
    forbidden: "Bu sayfaya erişim yetkiniz yok.",
  },
  language: {
    switcherLabel: "Dil",
  },
  footer: {
    tagline: "Güvenli sağlık karar destek yazılımı.",
    disclaimer:
      "Bu platform yalnızca karar destek bilgisi sunar. Profesyonel tıbbi değerlendirmenin yerini almaz.",
    copyright: "Health AI Platform Pro. Tüm hakları saklıdır.",
    links: {
      privacy: "Gizlilik",
      terms: "Koşullar",
      contact: "İletişim",
    },
  },
  landing: {
    badge: "Klinik karar destek platformu",
    heroTitle: "Sağlık ekipleri için daha akıllı klinik iş akışları",
    heroDescription:
      "Sağlık profesyonelleri için tasarlanmış güvenli bir çalışma alanında hasta kayıtlarını, sağlık içgörülerini ve risk değerlendirmelerini yönetin.",
    primaryCta: "Başlayın",
    secondaryCta: "Giriş yap",
    secondaryCtaAuthenticated: "Hastalara git",
    featuresTitle: "Sorumlu sağlık yapay zekası için tasarlandı",
    features: [
      {
        title: "Yapılandırılmış hasta verileri",
        description:
          "Randevuları, tıbbi kayıtları ve sağlık ölçümlerini yetkilendirilmiş erişim kontrolleriyle düzenleyin.",
      },
      {
        title: "Karar destek analitiği",
        description:
          "Tanı sunmadan klinik değerlendirmeyi destekleyen trendleri ve içgörüleri inceleyin.",
      },
      {
        title: "Ölçeklenebilir teknik temel",
        description:
          "FastAPI, JWT kimlik doğrulama, PostgreSQL kalıcılığı ve gözlemlenebilirlik ile büyüyen klinik iş yükleri için modüler bir mimari.",
      },
    ],
    trustTitle: "Klinik güvenlik öncelikli tasarım",
    trustPoints: [
      "Demo içeriğinde hasta tanımlayıcı bilgisi yok",
      "Karar destek çıktılarında açık tıbbi uyarılar",
      "Ortam yapılandırması üzerinden güvenli API entegrasyonu",
    ],
  },
  auth: {
    loginTitle: "Giriş yap",
    loginDescription: "Health AI Platform Pro hesabınızla çalışma alanınıza erişin.",
    registerTitle: "Hesap oluştur",
    registerDescription: "Klinik çalışma alanınız için profesyonel bir hesap oluşturun.",
    emailLabel: "E-posta adresi",
    emailPlaceholder: "siz@klinik.ornek",
    passwordLabel: "Şifre",
    passwordPlaceholder: "Şifrenizi girin",
    confirmPasswordLabel: "Şifreyi onayla",
    confirmPasswordPlaceholder: "Şifrenizi tekrar girin",
    loginSubmit: "Giriş yap",
    registerSubmit: "Hesap oluştur",
    noAccount: "Hesabınız yok mu?",
    hasAccount: "Zaten hesabınız var mı?",
    phaseNotice:
      "Yalnızca karar destek. Demo ortamlarda gerçek hasta tanımlayıcıları girmeyin.",
    firstNameLabel: "Ad",
    firstNamePlaceholder: "Ayşe",
    lastNameLabel: "Soyad",
    lastNamePlaceholder: "Yılmaz",
    loginError: "Giriş başarısız. E-posta ve şifrenizi kontrol edin.",
    registerError: "Kayıt başarısız. Farklı e-posta veya daha güçlü şifre deneyin.",
    passwordMismatch: "Şifreler eşleşmiyor.",
    genericError: "Bir sorun oluştu. Lütfen tekrar deneyin.",
    logout: "Çıkış yap",
    signedInAs: "Oturum:",
  },
  patients: {
    title: "Hastalar",
    description: "Klinik zaman tünelini görüntülemek için bir hasta seçin.",
    empty: "Hasta bulunamadı. API ile hasta ekleyin veya backend'de demo veri oluşturun.",
    viewTimeline: "Zaman tünelini görüntüle",
    viewPatient: "Hasta detayı",
    name: "Ad",
    dateOfBirth: "Doğum tarihi",
    gender: "Cinsiyet",
    loadError: "Hastalar yüklenemedi.",
    genders: {
      male: "Erkek",
      female: "Kadın",
      other: "Diğer",
    },
  },
  patientHub: {
    title: "Hasta özeti",
    description: "Atanmış hasta bilgilerini, risk geçmişini ve raporları inceleyin.",
    decisionSupportTitle: "Yalnızca klinik karar destek",
    decisionSupportBody:
      "Bu sistem tıbbi tanı koymaz. Bilgiler klinik karar destek amaçlıdır ve profesyonel tıbbi değerlendirmenin yerini almaz.",
    clinicalTimeline: "Klinik zaman tüneli",
    downloadPdf: "PDF raporu indir",
    downloadingPdf: "PDF hazırlanıyor…",
    pdfError: "PDF raporu indirilemedi.",
    pdfSuccess: "PDF indirme başlatıldı.",
    riskHistoryTitle: "Risk değerlendirme geçmişi",
    riskHistoryEmpty: "Bu hasta için henüz kayıtlı risk değerlendirmesi yok.",
    riskHistoryLoadError: "Risk geçmişi yüklenemedi.",
    riskType: "Tür",
    riskLevel: "Düzey",
    assessedAt: "Değerlendirme zamanı",
    score: "Skor",
    factors: "Katkı faktörleri",
    missingInputs: "Eksik girdiler",
    riskDisclaimer:
      "Risk çıktıları kural tabanlı karar destek tahminleridir; tanı veya tedavi planı değildir.",
    active: "Aktif",
    inactive: "Pasif",
    notFoundOrDenied: "Hasta bulunamadı veya bu hastaya erişim yetkiniz yok.",
    loadError: "Hasta bilgileri yüklenemedi.",
    assessmentTypes: {
      diabetes: "Diyabet",
      heart_disease: "Kalp hastalığı",
      stroke: "İnme",
    },
    riskLevels: {
      low: "Düşük",
      moderate: "Orta",
      elevated: "Yüksek",
    },
  },
  timeline: {
    title: "Klinik zaman tüneli",
    description: "Kayıtlı ölçümler, tıbbi kayıtlar ve randevuların salt okunur özeti.",
    sortNotice: "Olaylar eskiden yeniye gösterilir.",
    empty: "Seçilen dönemde timeline olayı yok.",
    loadError: "Klinik timeline yüklenemedi.",
    truncatedNotice: "Liste sınırına ulaşıldığı için bazı olaylar gösterilmedi.",
    filtersTitle: "Filtreler",
    dateFrom: "Başlangıç tarihi",
    dateTo: "Bitiş tarihi",
    applyFilters: "Filtreleri uygula",
    clearFilters: "Filtreleri temizle",
    includeRiskSnapshot: "Güncel risk anlık görüntüsünü dahil et",
    sourceKind: "Kaynak",
    severity: "Önem",
    disclaimer:
      "Bu klinik zaman tüneli, kayıtlı verilerin bilgilendirme amaçlı salt okunur özetidir. Tıbbi tanı, tedavi önerisi veya profesyonel tıbbi değerlendirmenin yerine geçmez. Türetilmiş öğeler, kayıtlı ölçüm ve randevuların kural tabanlı yorumlarıdır. Risk anlık görüntüleri, saklanan klinik geçmiş değil; yalnızca oluşturulma anındaki tek seferlik değerlendirmeyi yansıtır.",
    patientSummary: {
      ageSuffix: "yaş",
    },
    headlines: {
      "Diagnosis recorded": "Tanı kaydı",
      "Treatment noted": "Tedavi kaydı",
      "Medications noted": "İlaç kaydı",
      "Health measurement": "Sağlık ölçümü",
      "Appointment completed": "Randevu tamamlandı",
      "Appointment scheduled": "Planlanmış randevu",
      "Follow-up overdue": "Gecikmiş takip",
      "Blood Glucose trend increasing": "Kan şekeri yükseliş eğiliminde",
      "Systolic Pressure trend increasing": "Sistolik tansiyon yükseliş eğiliminde",
      "Diastolic Pressure trend increasing": "Diyastolik tansiyon yükseliş eğiliminde",
      "Clinical record": "Klinik kayıt",
      "Hospitalization recorded": "Hastaneye yatış kaydı",
      "Diabetes risk snapshot (current)": "Diyabet riski (güncel anlık görüntü)",
      "Heart disease risk snapshot (current)": "Kalp hastalığı riski (güncel anlık görüntü)",
      "Stroke risk snapshot (current)": "İnme riski (güncel anlık görüntü)",
    },
    sourceKinds: {
      medical_record: "Tıbbi kayıt",
      health_measurement: "Sağlık ölçümü",
      appointment: "Randevu",
      derived: "Türetilmiş analiz",
      risk_assessment_current_snapshot: "Güncel risk değerlendirmesi",
    },
    severityLevels: {
      info: "Bilgi",
      warning: "Uyarı",
      critical: "Kritik",
    },
    detailPhrases: {
      "Lifestyle modification and blood pressure monitoring":
        "Yaşam tarzı düzenlemesi ve tansiyon takibi",
      "Appointment recorded": "Randevu kaydedildi",
      "Health measurement recorded": "Sağlık ölçümü kaydedildi",
      Hypertension: "Hipertansiyon",
    },
    eventTypes: {
      medical_record_diagnosis: "Tıbbi kayıt",
      medical_record_treatment: "Tedavi",
      medical_record_medication: "İlaç",
      medical_record_hospitalization: "Hastaneye yatış",
      health_measurement: "Ölçüm",
      appointment_scheduled: "Randevu",
      appointment_completed: "Tamamlandı",
      appointment_cancelled: "İptal",
      appointment_status: "Randevu",
      appointment_overdue: "Geciken takip",
      measurement_trend_derived: "Trend analizi",
      risk_current_snapshot: "Risk anlık görüntüsü",
    },
  },
  management: {
    title: "Doktor atamaları",
    description:
      "Organizasyon üyeliğinizi görüntüleyin, doktorları listeleyin ve hastalara atama yönetin.",
    forbiddenTitle: "Erişim engellendi",
    forbiddenDescription:
      "Bu yönetim ekranı yalnızca klinik yöneticisi (clinic_admin) hesapları içindir.",
    organizationSection: "Organizasyon üyeliği",
    doctorsSection: "Aktif doktorlar",
    patientsSection: "Hasta seçimi",
    assignmentsSection: "Mevcut atamalar",
    assignDoctor: "Doktor ata",
    removeAssignment: "Atamayı kaldır",
    selectPatient: "Hasta seçin",
    selectDoctor: "Doktor seçin",
    noPatientSelected: "Atamaları görmek için listeden bir hasta seçin.",
    membershipId: "Üyelik kimliği",
    organizationId: "Organizasyon kimliği",
    membershipRole: "Üyelik rolü",
    joinedAt: "Katılım tarihi",
    userId: "Kullanıcı kimliği",
    patientLabel: "Hasta",
    isPrimary: "Birincil atama",
    status: "Durum",
    assignedAt: "Atama tarihi",
    endedAt: "Bitiş tarihi",
    assignmentId: "Atama kimliği",
    assigneeUserId: "Atanan doktor kimliği",
    emptyDoctors: "Organizasyonda listelenecek aktif doktor yok.",
    emptyAssignments: "Bu hasta için kayıtlı atama yok.",
    loadError: "Yönetim verileri yüklenemedi.",
    createSuccess: "Atama oluşturuldu.",
    deactivateSuccess: "Atama devre dışı bırakıldı.",
    membershipRoles: {
      doctor: "Doktor",
      clinic_admin: "Klinik yöneticisi",
    },
    assignmentStatuses: {
      active: "Aktif",
      inactive: "Pasif",
    },
    errors: {
      duplicateAssignment:
        "Bu doktor ve hasta için zaten aktif bir atama var.",
      duplicatePrimary: "Bu hasta için zaten aktif bir birincil atama var.",
      patientNotFound: "Hasta bulunamadı veya organizasyonunuz dışında.",
      assignmentNotFound: "Atama bulunamadı.",
      doctorNotFound: "Doktor bulunamadı veya organizasyonunuz dışında.",
      generic: "İşlem tamamlanamadı. Lütfen tekrar deneyin.",
    },
  },
};
